export const future = ['Golang', 'Elixir'];

export const nonTechnical = [
	'Search engine optimization',
	'Search engine marketing',
	'Content marketing',
	'Graphic design',
	'User interface design',
	'User experience design',
	'Conversion rate optimization',
	'Video editing',
	'Copywriting',
	'E-commerce',
];

export const technical = [
	'HTML',
	'CSS',
	'JavaScript',
	'TypeScript',
	'Svelte',
	'SvelteKit',
	'React',
	'Redux',
	'Gatsby.js',
	'Next.js',
	'Node.js',
	'SQL',
	'Supabase',
	'NoSQL',
	'MongoDB',
	'GraphQL',
	'TailwindCSS',
	'Jest',
	'Vitest',
	'Playwright',
	'D3.js',
	'Babel',
	'Webpack',
	'ESLint',
	'Git',
];
